/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rversedesigner;

import au.com.bytecode.opencsv.CSVReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hafeez
 */
public class ListofProjects extends javax.swing.JFrame {
protected JFrame localFrame;
    /**
     * Creates new form ListofProjects_Text
     */
    
public ListofProjects() {
        initComponents();
    }

public void setListofProjects(String masterCSV){
        String [] row = null;
        String csvFileStr = masterCSV;        
        CSVReader csvReadProj = null;
        String[] rowInput = null;
       
        System.out.println("This is master file :" + masterCSV);
        
        try {
            if (csvFileStr != ""){
                csvReadProj = new CSVReader (new FileReader(csvFileStr));
                try {
                    rowInput = csvReadProj.readNext();
                } catch (IOException ex) {
                        Logger.getLogger(TextMiningMetrics.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TextMiningMetrics.class.getName()).log(Level.SEVERE, null, ex);
            }
        int count = 3;   
        System.out.println(rowInput.length);
        while (count <= rowInput.length - 1){            
            listofProjects.add(rowInput[count]);
            count++;
        }   
}

public Object[] setProjectList(String masterCSV){
        String [] row = null;
        String csvFileStr = masterCSV;        
        CSVReader csvReadProj = null;
        String[] rowInput = null;
        ArrayList<String> listProj = new ArrayList<String>();
        //Object[] listProjects = null;
        
        System.out.println("This is master file :" + masterCSV);
        
        try {
            if (csvFileStr != ""){
                csvReadProj = new CSVReader (new FileReader(csvFileStr));
                try {
                    rowInput = csvReadProj.readNext();
                } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Text Mining File Not Found");
                        Logger.getLogger(TextMiningMetrics.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Text Mining File Not Found");
                Logger.getLogger(TextMiningMetrics.class.getName()).log(Level.SEVERE, null, ex);
            }
        int count = 3;   
        System.out.println(rowInput.length);
        while (count <= rowInput.length - 1){            
            listProj.add(rowInput[count]);
            count++;
        }   
        Object[] listProjects = listProj.toArray();
    return listProjects;
}

public void clearList(){
    listofProjects.removeAll();
}

public int selectedProject(){
    return listofProjects.getSelectedIndex();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applyProject = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        projectSelection = new javax.swing.JLabel();
        listofProjects = new java.awt.List();

        setTitle("Select");
        setBackground(new java.awt.Color(153, 204, 255));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setResizable(false);

        applyProject.setText("Apply");
        applyProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyProjectActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        projectSelection.setText("Please select your project");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listofProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectSelection)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(applyProject, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancel)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(projectSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listofProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyProject)
                    .addComponent(cancel))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void applyProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyProjectActionPerformed
        // TODO add your handling code here:               
    }//GEN-LAST:event_applyProjectActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Selected : " + listofProjects.getSelectedIndex());
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListofProjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListofProjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListofProjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListofProjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListofProjects().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyProject;
    private javax.swing.JButton cancel;
    private java.awt.List listofProjects;
    private javax.swing.JLabel projectSelection;
    // End of variables declaration//GEN-END:variables
}
